/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CategoryRouteImport } from './routes/$category'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as CategoryShootRouteImport } from './routes/$category/$shoot'
import { Route as ApiCloudinaryUploadRouteImport } from './routes/api/cloudinary/upload'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryShootRoute = CategoryShootRouteImport.update({
  id: '/$shoot',
  path: '/$shoot',
  getParentRoute: () => CategoryRoute,
} as any)
const ApiCloudinaryUploadRoute = ApiCloudinaryUploadRouteImport.update({
  id: '/api/cloudinary/upload',
  path: '/api/cloudinary/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/about': typeof AboutRoute
  '/pricing': typeof PricingRoute
  '/$category/$shoot': typeof CategoryShootRoute
  '/admin/media': typeof AdminMediaRoute
  '/api/cloudinary/upload': typeof ApiCloudinaryUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/about': typeof AboutRoute
  '/pricing': typeof PricingRoute
  '/$category/$shoot': typeof CategoryShootRoute
  '/admin/media': typeof AdminMediaRoute
  '/api/cloudinary/upload': typeof ApiCloudinaryUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/about': typeof AboutRoute
  '/pricing': typeof PricingRoute
  '/$category/$shoot': typeof CategoryShootRoute
  '/admin/media': typeof AdminMediaRoute
  '/api/cloudinary/upload': typeof ApiCloudinaryUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$category'
    | '/about'
    | '/pricing'
    | '/$category/$shoot'
    | '/admin/media'
    | '/api/cloudinary/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$category'
    | '/about'
    | '/pricing'
    | '/$category/$shoot'
    | '/admin/media'
    | '/api/cloudinary/upload'
  id:
    | '__root__'
    | '/'
    | '/$category'
    | '/about'
    | '/pricing'
    | '/$category/$shoot'
    | '/admin/media'
    | '/api/cloudinary/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRouteWithChildren
  AboutRoute: typeof AboutRoute
  PricingRoute: typeof PricingRoute
  AdminMediaRoute: typeof AdminMediaRoute
  ApiCloudinaryUploadRoute: typeof ApiCloudinaryUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category': {
      id: '/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$shoot': {
      id: '/$category/$shoot'
      path: '/$shoot'
      fullPath: '/$category/$shoot'
      preLoaderRoute: typeof CategoryShootRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/api/cloudinary/upload': {
      id: '/api/cloudinary/upload'
      path: '/api/cloudinary/upload'
      fullPath: '/api/cloudinary/upload'
      preLoaderRoute: typeof ApiCloudinaryUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CategoryRouteChildren {
  CategoryShootRoute: typeof CategoryShootRoute
}

const CategoryRouteChildren: CategoryRouteChildren = {
  CategoryShootRoute: CategoryShootRoute,
}

const CategoryRouteWithChildren = CategoryRoute._addFileChildren(
  CategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRouteWithChildren,
  AboutRoute: AboutRoute,
  PricingRoute: PricingRoute,
  AdminMediaRoute: AdminMediaRoute,
  ApiCloudinaryUploadRoute: ApiCloudinaryUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
